### ISSUE TITLE
Unexpected \a between selectors 

### ISSUE THREAD

**Issue by dennisfrank** [sass/libsass#1328]
I stumbled over following issue:

http://sassmeister.com/gist/51e6f8724f98f49ffcf4

```
@mixin foo($foo: bar) {
  .#{$foo}:before,
  [data-attribute="#{$foo}"]:before,
  [data-another-attribute="#{$foo}"]:before {
    content: "whatever";
  }
}

@include foo;
```

will become

```
.bar:before,
[data-attribute="bar"]:before, \a [data-another-attribute="bar"]:before {
    content: "whatever";
}
````

instead of

```
.bar:before,
[data-attribute="bar"]:before,
[data-another-attribute="bar"]:before {
    content: "whatever";
}
```

**The line-break between the second and third selector gets replaced by `\a` and breaks the CSS.**

If you remove `.#{$foo}:before,` or append a space or another character to the data-attribute value like `[data-attribute="#{$foo} "]:before,` the `\a` disappears but the CSS is wrong.

As a crude workaround you can replace the double quotes of one(!) selector with single quotes:

```
@mixin foo($foo: bar) {
  .#{$foo}:before,
  [data-attribute='#{$foo}']:before,
  [data-another-attribute="#{$foo}"]:before {
    content: "whatever";
  }
}

@include foo;
```

will become

```
.bar:before,
[data-attribute='bar']:before,
[data-another-attribute="bar"]:before {
    content: "whatever";
}
````

When both selectors contain the same quotes (double or single) it breaks again.

**Comment by mgreter** [comment]
This seems already fixed with my latest refactoring branch (//CC @xzyfer)

**Comment by dennisfrank** [comment]
@mgreter @xzyfer If this is already fixed, that would be great! 

BTW same issue with `@each`:

```
@each $item, $value in $items {
	.#{$foo}:before,
	[data-attribute="#{$foo}"]:before,
	[data-another-attribute="#{$foo}"]:before {
		content: "whatever";
  }
}
```

**Comment by xzyfer** [comment]
I've seen a couple reports of this. It'd be good to have a failing test case to ensure this doesn't regress. I'll work it.

**Comment by xzyfer** [comment]
Spec added https://github.com/sass/sass-spec/pull/446

**Comment by mgreter** [comment]
it seems that the fix for this is somewhere burried in one of my refactorings ...

**Comment by mgreter** [comment]
IMO this is not fixed yet, waiting for that fix to come up ...

**Comment by mgreter** [comment]
It seems this problem only happens if you use windows linefeeds ...

**Comment by dennisfrank** [comment]
Hm. This file has LF unix line endings: http://cl.ly/code/2Y21191G2S3p/download/test.app.scss

Same problem.

**Comment by mgreter** [comment]
The whole thing was a lot weirder and has indeed to do with how we parse css strings (@xzyfer this is actually where the differences between static and quoted strings come into play). Anyway, I think I have a proper fix in https://github.com/sass/libsass/issues/1349!

**Comment by xzyfer** [comment]
For what it's worth I was able to reproduce this 100% on OSX
